### ISSUE TITLE
READMEの整備

### ISSUE THREAD

**Issue by 618knot** [618knot/SODH_2023_CIeaST#1]

**Comment by 618knot** [comment]
とくにブランチにへんこぅがあるわけじゃないのでPRは立てないです
とりあえずREADME読んでなんかあったらコメント残してくださいな

↓読んだらチェック入れて
- [x] @kiryu-3 
- [x] @shinjinhakase

**Comment by kiryu-3** [comment]
以前のチーム開発で全く役に立てずに足を引っ張り、
若干病んだ経験があるのでお手柔らかにお願いします…
