### ISSUE TITLE
SQLを実行する処理をつくる

### ISSUE THREAD

**Issue by 618knot** [618knot/SODH_2023_CIeaST#3]
CRUD処理を実装してみたところ、この辺はある程度関数化しておけそうなので、関数化しておく
実装する関数以下2つ
- SELECTを実行できる関数
```py
def execute_query(sql: str) -> list:
    pass
```
- CREATE, UPDATE, DELETEを実行できる関数
```py
def execute_update(sql: str) -> None:
    pass
```

### 注意点
- `execute_update`関数については、CREATE, UPDATE, DELETEが複数のレコードを制御する場合についても考慮すること(ヒント: `executemany`が使えそう)
- 関数の実装場所についても考慮すること

**Comment by kiryu-3** [comment]
@618knot 
こんな感じかなーと思うんですが、どうでしょうか、、
全然わかっていないもので。どこにpushするのかとか、関数の実装場所についてとか。
``` database_operations.py
from sqlite3 import connect, Cursor, Connection
from .util.sqlite_util import *

# ここがよく分かりません
def generate_connect() -> Connection:
    # データベース接続を生成するロジックを実装
    # 例: return connect('database.db')
    pass

def execute_query(sql: str) -> list:
    conn: Connection = generate_connect()
    cursor: Cursor = conn.cursor()
    cursor.execute(sql)  # SQLクエリを実行
    result = cursor.fetchall()  # 結果を取得
    connection.close()  # 接続を閉じる
    return result

def execute_update(sql: str, data: list) -> None:
    conn: Connection = generate_connect()
    cursor: Cursor = conn.cursor()
    if data:
        cursor.executemany(sql, data)  # 複数のレコードを処理
    else:
        cursor.execute(sql)  # 1つのクエリを実行
    connection.commit()  # 変更をコミット
    connection.close()  # 接続を閉じる
```
#

**Comment by 618knot** [comment]
それはどこのファイル？

**Comment by kiryu-3** [comment]
実装する関数2つを書いてみただけで、どこのファイルというわけでもない（場所が分からないのでpushはしてない）

**Comment by 618knot** [comment]
[routers/demo_users.py](https://github.com/618knot/SODH_2023_CIeaST/blob/main/app/routers/demo_users.py), [routers/util/sqlite_util.py](https://github.com/618knot/SODH_2023_CIeaST/blob/main/app/routers/util/sqlite_util.py)あたりを一回読んでみて、どこに実装するのか考えてみてほしい
[demo_users.py](https://github.com/618knot/SODH_2023_CIeaST/blob/main/app/routers/demo_users.py)でcrud処理をそれぞれ実装していて、今回は実装する2つの関数を使って[demo_users.py](https://github.com/618knot/SODH_2023_CIeaST/blob/main/app/routers/demo_users.py)のsql処理を短くしたいという狙い
