### ISSUE TITLE
websocketでチャットツールを作成する方法を検討する

### ISSUE THREAD

**Issue by shinjinhakase** [618knot/SODH_2023_CIeaST#6]
- [ ] チャットルームの作成
- [ ] チャットルームの閲覧
- [ ] メッセージの保存
- [ ] リアルタイムでの反映
- [ ] 送信相手の画面でメッセージを取得

**Comment by 618knot** [comment]
https://qiita.com/satto_sann/items/a62cb030e5c631eb74ad

**Comment by 618knot** [comment]
https://fastapi.tiangolo.com/ja/advanced/websockets/

**Comment by shinjinhakase** [comment]
- 借りたい人がチャットルームを作成する
- チャットルームが作られるとデータベースに保存される
- 借りたい人がメッセージを送ったとき、クッキーを参照して人を特定し、メッセージ内容を取得してメッセージを作成し、データベースに保存する
- websocketで画面に表示する
- メッセージはチャットルームの子要素として紐づけられる
- オーナーがログインしたとき、そのオーナーがかかわるチャットルームが存在するか確認する
- オーナーが未読のチャットがあったら通知する
- 借りる人がその後にログインした場合も通知する
- メッセージは既読、未読のカラムをもつ

**Comment by shinjinhakase** [comment]
チャットルームのスキーマ
- チャットルームのID
- 借りたい人のユーザID
- オーナーのユーザID
- 駐車場のID

メッセージのスキーマ
- チャットルームのID
- 送信者のユーザID
- メッセージの送信時間
- 既読フラグ
